
  create table "public"."articles" (
    "id" bigint generated by default as identity not null,
    "title" text not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now()
      );


alter table "public"."articles" enable row level security;


  create table "public"."comment_tree_paths" (
    "ancestor_id" bigint not null,
    "descendant_id" bigint not null,
    "depth" integer not null default 0
      );


alter table "public"."comment_tree_paths" enable row level security;


  create table "public"."comments" (
    "id" bigint generated by default as identity not null,
    "article_id" bigint not null,
    "parent_id" bigint,
    "author_name" text not null,
    "body" text not null,
    "created_at" timestamp with time zone not null default now(),
    "deleted_at" timestamp with time zone
      );


alter table "public"."comments" enable row level security;

CREATE UNIQUE INDEX articles_pkey ON public.articles USING btree (id);

CREATE UNIQUE INDEX comment_tree_paths_pkey ON public.comment_tree_paths USING btree (ancestor_id, descendant_id);

CREATE UNIQUE INDEX comments_pkey ON public.comments USING btree (id);

CREATE INDEX idx_comment_tree_paths_ancestor_depth ON public.comment_tree_paths USING btree (ancestor_id, depth);

CREATE INDEX idx_comment_tree_paths_descendant ON public.comment_tree_paths USING btree (descendant_id);

CREATE INDEX idx_comments_article_id ON public.comments USING btree (article_id);

CREATE INDEX idx_comments_deleted_at ON public.comments USING btree (deleted_at);

CREATE INDEX idx_comments_parent_id ON public.comments USING btree (parent_id);

alter table "public"."articles" add constraint "articles_pkey" PRIMARY KEY using index "articles_pkey";

alter table "public"."comment_tree_paths" add constraint "comment_tree_paths_pkey" PRIMARY KEY using index "comment_tree_paths_pkey";

alter table "public"."comments" add constraint "comments_pkey" PRIMARY KEY using index "comments_pkey";

alter table "public"."comment_tree_paths" add constraint "comment_tree_paths_ancestor_id_fkey" FOREIGN KEY (ancestor_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comment_tree_paths" validate constraint "comment_tree_paths_ancestor_id_fkey";

alter table "public"."comment_tree_paths" add constraint "comment_tree_paths_depth_check" CHECK ((depth >= 0)) not valid;

alter table "public"."comment_tree_paths" validate constraint "comment_tree_paths_depth_check";

alter table "public"."comment_tree_paths" add constraint "comment_tree_paths_descendant_id_fkey" FOREIGN KEY (descendant_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comment_tree_paths" validate constraint "comment_tree_paths_descendant_id_fkey";

alter table "public"."comments" add constraint "comments_article_id_fkey" FOREIGN KEY (article_id) REFERENCES public.articles(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_article_id_fkey";

alter table "public"."comments" add constraint "comments_parent_id_fkey" FOREIGN KEY (parent_id) REFERENCES public.comments(id) ON DELETE CASCADE not valid;

alter table "public"."comments" validate constraint "comments_parent_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_comment_tree_path_insert()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
BEGIN
  -- 自己参照行を挿入（depth = 0）
  INSERT INTO public.comment_tree_paths (ancestor_id, descendant_id, depth)
  VALUES (NEW.id, NEW.id, 0);

  -- 親がある場合、親の全先祖パスをコピーして新ノードに接続
  IF NEW.parent_id IS NOT NULL THEN
    INSERT INTO public.comment_tree_paths (ancestor_id, descendant_id, depth)
    SELECT
      ctp.ancestor_id,
      NEW.id,
      ctp.depth + 1
    FROM public.comment_tree_paths ctp
    WHERE ctp.descendant_id = NEW.parent_id;
  END IF;

  RETURN NEW;
END;
$function$
;

grant delete on table "public"."articles" to "anon";

grant insert on table "public"."articles" to "anon";

grant references on table "public"."articles" to "anon";

grant select on table "public"."articles" to "anon";

grant trigger on table "public"."articles" to "anon";

grant truncate on table "public"."articles" to "anon";

grant update on table "public"."articles" to "anon";

grant delete on table "public"."articles" to "authenticated";

grant insert on table "public"."articles" to "authenticated";

grant references on table "public"."articles" to "authenticated";

grant select on table "public"."articles" to "authenticated";

grant trigger on table "public"."articles" to "authenticated";

grant truncate on table "public"."articles" to "authenticated";

grant update on table "public"."articles" to "authenticated";

grant delete on table "public"."articles" to "service_role";

grant insert on table "public"."articles" to "service_role";

grant references on table "public"."articles" to "service_role";

grant select on table "public"."articles" to "service_role";

grant trigger on table "public"."articles" to "service_role";

grant truncate on table "public"."articles" to "service_role";

grant update on table "public"."articles" to "service_role";

grant delete on table "public"."comment_tree_paths" to "anon";

grant insert on table "public"."comment_tree_paths" to "anon";

grant references on table "public"."comment_tree_paths" to "anon";

grant select on table "public"."comment_tree_paths" to "anon";

grant trigger on table "public"."comment_tree_paths" to "anon";

grant truncate on table "public"."comment_tree_paths" to "anon";

grant update on table "public"."comment_tree_paths" to "anon";

grant delete on table "public"."comment_tree_paths" to "authenticated";

grant insert on table "public"."comment_tree_paths" to "authenticated";

grant references on table "public"."comment_tree_paths" to "authenticated";

grant select on table "public"."comment_tree_paths" to "authenticated";

grant trigger on table "public"."comment_tree_paths" to "authenticated";

grant truncate on table "public"."comment_tree_paths" to "authenticated";

grant update on table "public"."comment_tree_paths" to "authenticated";

grant delete on table "public"."comment_tree_paths" to "service_role";

grant insert on table "public"."comment_tree_paths" to "service_role";

grant references on table "public"."comment_tree_paths" to "service_role";

grant select on table "public"."comment_tree_paths" to "service_role";

grant trigger on table "public"."comment_tree_paths" to "service_role";

grant truncate on table "public"."comment_tree_paths" to "service_role";

grant update on table "public"."comment_tree_paths" to "service_role";

grant delete on table "public"."comments" to "anon";

grant insert on table "public"."comments" to "anon";

grant references on table "public"."comments" to "anon";

grant select on table "public"."comments" to "anon";

grant trigger on table "public"."comments" to "anon";

grant truncate on table "public"."comments" to "anon";

grant update on table "public"."comments" to "anon";

grant delete on table "public"."comments" to "authenticated";

grant insert on table "public"."comments" to "authenticated";

grant references on table "public"."comments" to "authenticated";

grant select on table "public"."comments" to "authenticated";

grant trigger on table "public"."comments" to "authenticated";

grant truncate on table "public"."comments" to "authenticated";

grant update on table "public"."comments" to "authenticated";

grant delete on table "public"."comments" to "service_role";

grant insert on table "public"."comments" to "service_role";

grant references on table "public"."comments" to "service_role";

grant select on table "public"."comments" to "service_role";

grant trigger on table "public"."comments" to "service_role";

grant truncate on table "public"."comments" to "service_role";

grant update on table "public"."comments" to "service_role";


  create policy "articles_select_policy"
  on "public"."articles"
  as permissive
  for select
  to anon
using (true);



  create policy "comment_tree_paths_select_policy"
  on "public"."comment_tree_paths"
  as permissive
  for select
  to anon
using (true);



  create policy "comments_insert_policy"
  on "public"."comments"
  as permissive
  for insert
  to anon
with check (true);



  create policy "comments_select_policy"
  on "public"."comments"
  as permissive
  for select
  to anon
using (true);



  create policy "comments_update_policy"
  on "public"."comments"
  as permissive
  for update
  to anon
using (true)
with check (true);


CREATE TRIGGER on_comment_inserted AFTER INSERT ON public.comments FOR EACH ROW EXECUTE FUNCTION public.handle_comment_tree_path_insert();


